# Student details
first_name = input("Enter the first name of the student: ")
last_name = input("Enter the last name of the student: ")
age = input("Enter the age of the student: ")
place = input("Enter the place of residence: ")
print("\nStudent Details:")
print("----------------")
print("Student name is: "+first_name+" "+last_name)
print("Age: ",age)
print("Place: ",place)